### ISSUE TITLE
"Avoid non-composited animations"

### ISSUE THREAD

**Issue by GipHub123** [willmendesneto/ngx-skeleton-loader#52] opened 2020-11-30 18:09 UTC
**I'm submitting a ...** (check one with "x")

- [ ] bug report => search github for a similar issue or PR before submitting
- [ x] feature request

**Current behavior**

I tested application's performance using Chrome's Lighthouse plugin. 

![unsupported](https://user-images.githubusercontent.com/12637608/100647096-b35f6480-3347-11eb-9e70-de2e90ae2d0d.png)

Lighthouse shows warnings from ngx-skeleton-loader.scss -file (progress).  

* "Avoid non-composited animations":
* "Animations which are not composited can be janky and contribute to CLS"

I don't know much about CSS animation. 
**Just wondering if this is something that can be fixed?** 

Links:

https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=en
https://developers.google.com/web/fundamentals/performance/rendering/stick-to-compositor-only-properties-and-manage-layer-count?utm_source=lighthouse&utm_medium=devtools

And thanks for the great library. It's really easy to use :) 

**Expected behavior**

Lighthouse plugin doesn't show warnings about  non-composited animations. 

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

Please tell us about your environment:

"ngx-skeleton-loader": "^2.6.1",

Angular CLI: 11.0.2
Node: 10.18.1
OS: win32 x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes
Package Version

@angular-devkit/architect 0.1100.0
@angular-devkit/build-angular 0.1100.2
@angular-devkit/core 11.0.0
@angular-devkit/schematics 11.0.2
@angular/cdk 11.0.0
@angular/material 11.0.0
@angular/material-moment-adapter 11.0.0
@nguniversal/builders 11.0.0
@nguniversal/express-engine 11.0.0
@schematics/angular 11.0.2
@schematics/update 0.1100.2
rxjs 6.6.3
typescript 4.0.5

**Comment by willmendesneto** [comment] 2020-12-06 07:38
Hey @GipHub123 Thanks for raising this issue. I'll have a look at that in the next days and share my updates here.

**Comment by willmendesneto** [comment] 2020-12-08 07:59
Hi @GipHub123 , sharing some great news!

I'm happy to share the issue was fixed in [this commit](https://github.com/willmendesneto/ngx-skeleton-loader/commit/034721483953ffd2f2c14da7969058e1904cd698) and the problem is solved. Also, since it's using `translate3d` instead of background-position for animation, the module now got a massive performance boost for CSS animations 🎉

Please update your project to use `ngx-skeleton-loader@2.6.2` to solve this issue in your project. And, one more time, thanks for raising this issue!

**Closed by willmendesneto** 2020-12-08 07:59 UTC
