### ISSUE TITLE
Error Type '"lines"' is not assignable to type '"" | "circle

### ISSUE THREAD

**Issue by supervardon** [willmendesneto/ngx-skeleton-loader#60] opened 2021-02-19 10:13 UTC
After an issue solved yesterday, we are now getting an error with Angular 11.  

`Type '"lines"' is not assignable to type '"" | "circle"'.`

If it helps, this error does go away after setting ` "strictTemplates": false` in the angularcompileroptions.

**Comment by willmendesneto** [comment] 2021-02-19 21:31
Thanks for raising this issue @supervardon.

I took a look at your issue and looks like you added an appearance that doesn't exist. So the problem is your configuration. There's no appearance for `lines`. What you calling that way is the default appearance of the skeleton.

If you remove that it should work as expected. You also can take a look at the Stackblitz demos to check different ways to use the module and components. https://stackblitz.com/edit/ngx-skeleton-loader-sample

I'll add more documentation on the `README.md` to avoid other developers having a similar problem and close this issue.

**Closed by willmendesneto** 2021-02-19 21:31 UTC

**Comment by supervardon** [comment] 2021-03-06 18:44
Thanks for responding and fixing so quickly.  Love the product btw
