### ISSUE TITLE
Does this library support custom SVG shapes?

### ISSUE THREAD

**Issue by dolanmiu** [willmendesneto/ngx-skeleton-loader#53] opened 2021-01-06 18:01 UTC
I have this use case where a donut chart is displayed.

Therefore the loading skeleton has to be a donut shape

Is this possible?

Thanks

**Comment by willmendesneto** [comment] 2021-01-08 19:04
Hi @dolanmiu . Thanks for raising this issue!

At the moment this is not possible by design. This module tries to be lightweight and simple as possible, having other complex manipulations being delegated to the consumers, such as specific animations, theming, etc.

Not sure if I understood your scenario, but since it's something too exclusive/specific, looks like what you want will be just a matter to add an SVG directly into your project.

In any case, could you share more details about your scenario, please? It would be great to get more context about the feature request itself and see how that could/will be a great benefit for everyone.

**Comment by willmendesneto** [comment] 2021-01-16 18:18
Closing this issue due to the lack of replies. Thanks @dolanmiu  , feel free to reopen it if needed.

**Closed by willmendesneto** 2021-01-16 18:18 UTC
